# Generated by Django 2.0.5 on 2018-05-15 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.TextField(choices=[('DEPORTIVO', 'Deportivo'), ('MÚSICAL', 'Músical'), ('CULTURAL', 'Cultural'), ('OTRO', 'Otro')], default='CULTURAL', verbose_name='Tipo')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Precio')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.TextField(choices=[('MEAÑO', 'Meaño'), ('SANXENXO', 'Sanxenxo'), ('CAMBADOS', 'Cambados')], default='MEAÑO', verbose_name='Concello')),
                ('district', models.TextField(choices=[('ADINA', 'Adina'), ('ARRA', 'Arra'), ('BORDÓNS', 'Bordóns'), ('DORRÓN', 'Dorrón'), ('GONDAR', 'Gondar'), ('NANTES', 'Nantes'), ('NOALLA', 'Noalla'), ('PADRIÑÁN', 'Padriñán'), ('VILALONGA', 'Vilalonga'), ('CAMBADOS', 'Cambados'), ('CASTRELO', 'Castrelo'), ('CORVILLÓN', 'Corvillón'), ('OUBIÑA', 'Oubiña'), ('DENA', 'Dena'), ('PADRENDA', 'Padrenda'), ('LORES', 'Lores'), ('SIMES', 'Simes'), ('MEAÑO', 'Meaño'), ('XIL', 'Xil'), ('COBAS', 'Cobas')], default='MEAÑO', verbose_name='Parroquia')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
