# Generated by Django 2.0.5 on 2018-05-31 13:22

import core.services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modificado')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('title', models.CharField(max_length=100, verbose_name='Nombre del evento')),
                ('description', models.TextField()),
                ('category', models.TextField(choices=[('ARTÍSTICO', 'Artístico'), ('CULTURAL', 'Cultural'), ('DEPORTIVO', 'Deportivo'), ('GASTRONÓMICO', 'Gastronómico'), ('MÚSICAL', 'Músical'), ('OTRO', 'Otro')], default='CULTURAL', verbose_name='Tipo')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Precio')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=core.services.generate_unique_file_path, verbose_name='Imagen')),
                ('duration', models.TextField(blank=True, choices=[('Todo el día', 'Día completo'), ('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Fin de semana ', 'Fin de semana')], null=True, verbose_name='Duración')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='modificado')),
                ('council', models.TextField(choices=[('CAMBADOS', 'Cambados'), ('O GROVE', 'O Grove'), ('ILLA DE AROUSA', 'Illa de Arousa'), ('MEAÑO', 'Meaño'), ('MEIS', 'Meis'), ('RIBADUMIA', 'Ribadumia'), ('SANXENXO', 'Sanxenxo'), ('VILAGARCÍA', 'Vilagarcía'), ('VILANOVA', 'Vilanova')], default='MEAÑO', verbose_name='Concello')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parroquia')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
