# Generated by Django 2.0.5 on 2018-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='council',
            field=models.TextField(choices=[('MEAÑO', 'Meaño'), ('SANXENXO', 'Sanxenxo'), ('CAMBADOS', 'Cambados')], default='MEAÑO', verbose_name='Concello'),
        ),
    ]
