# Generated by Django 2.0.5 on 2018-05-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='council',
            field=models.TextField(choices=[('CAMBADOS', 'Cambados'), ('O GROVE', 'O Grove'), ('ILLA DE AROUSA', 'Illa de Arousa'), ('MEAÑO', 'Meaño'), ('MEIS', 'Meis'), ('RIBADUMIA', 'Ribadumia'), ('SANXENXO', 'Sanxenxo'), ('VILAGARCÍA DE AROUSA', 'Vilagarcía'), ('VILANOVA', 'Vilanova')], default='MEAÑO', verbose_name='Concello'),
        ),
    ]
