# Generated by Django 2.0.5 on 2018-06-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180531_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(choices=[('ARTE', 'Arte'), ('CULTURA', 'Cultura'), ('DEPORTE', 'Deporte'), ('GASTRONOMÍA', 'Gastronomía'), ('MÚSICA', 'Música'), ('OTRO', 'Otro')], default='CULTURAL', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
    ]
