# Generated by Django 2.0.5 on 2018-05-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pointofinterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
    ]
