# Generated by Django 2.0.5 on 2018-05-16 13:59

from django.db import migrations
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_pointofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='position',
            field=geoposition.fields.GeopositionField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
    ]
