# Generated by Django 2.0.5 on 2018-05-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_place_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='position',
        ),
    ]
