# Generated by Django 2.0.5 on 2018-05-18 08:00

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_place_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
