# Generated by Django 2.0.5 on 2018-05-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_place_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TextField(blank=True, choices=[('Todo el día', 'Día completo'), ('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche'), ('Fin de semana ', 'Fin de semana')], null=True, verbose_name='Duración'),
        ),
    ]
