# Generated by Django 2.0.5 on 2018-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180528_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parroquia'),
        ),
    ]
