# Generated by Django 2.0.5 on 2018-05-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
