# Generated by Django 2.0.5 on 2018-05-28 15:16

import core.widgets
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='location',
            field=core.widgets.LocationField(blank=True, max_length=255),
        ),
    ]
