# Generated by Django 2.0.5 on 2018-05-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180530_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='position',
        ),
    ]
