# Generated by Django 2.0.5 on 2018-05-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180531_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
